// AUTO-GENERATED by scripts/build-disclaimers.ts. Do not edit directly.
// Edit docs/legal/disclaimers.md and run `npm run build:disclaimers`.
import json from './disclaimers.json' with { type: 'json' };
export const DISCLAIMERS = json as Readonly<{
  preOutputFraming: string;
  fareActFraming: string;
  affiliateClickThrough: string;
  affiliateLongForm: string;
  weAreNotFooter: string;
}>;
