/**
 * Phase 0.3 acceptance verifier.
 *
 * Hits every NYC Open Data Socrata endpoint listed in `docs/data-sources.md`
 * with `$limit=1`, asserts the response is HTTP 200, and asserts the
 * documented primary-key field is present in the returned row.
 *
 * Reads `NYC_OPEN_DATA_APP_TOKEN` from env if set (raises rate limit from
 * ~1k/hr to ~10k/hr per token, but the script works without one).
 *
 * Run:
 *   npm run verify:data-sources
 *   NYC_OPEN_DATA_APP_TOKEN=xxx npm run verify:data-sources
 *
 * Exits with code 0 on full pass, 1 on any failure. CI-friendly.
 */

import { config as loadDotenv } from "dotenv";

export interface Endpoint {
  /** Human label for log output. */
  label: string;
  /** Socrata resource id. */
  resourceId: string;
  /** Field that must exist in any non-empty response (the documented PK). */
  primaryKey: string;
  /**
   * Primary keys we'll accept in addition to the canonical one. Useful for
   * datasets where Socrata's stable id is the autogenerated `:id` rather
   * than a domain field — we treat `:id` as a valid fallback so the script
   * doesn't false-fail on schema drift.
   */
  alternatePrimaryKeys?: string[];
}

export const ENDPOINTS: Endpoint[] = [
  {
    label: "HPD Housing Maintenance Code Violations",
    resourceId: "wvxf-dwi5",
    primaryKey: "violationid",
  },
  {
    label: "HPD Multiple Dwelling Registrations",
    resourceId: "tesw-yqqr",
    primaryKey: "registrationid",
  },
  {
    label: "HPD Registration Contacts",
    resourceId: "feu5-w2e2",
    primaryKey: "registrationcontactid",
  },
  {
    label: "DOB Complaints Received",
    resourceId: "eabe-havv",
    primaryKey: "complaint_number",
  },
  {
    label: "311 Service Requests (2020 - Present)",
    resourceId: "erm2-nwe9",
    primaryKey: "unique_key",
  },
  {
    label: "NYC Marshal Evictions",
    resourceId: "6z8x-wfk4",
    primaryKey: "court_index_number",
  },
  {
    label: "Bedbug Reporting",
    resourceId: "wz6d-d3jb",
    // The bedbug dataset's domain key has shifted over the years; accept any
    // of these. Socrata always exposes its stable `:id` as well.
    primaryKey: "building_id",
    alternatePrimaryKeys: [":id", "buildingid", "registrationid"],
  },
  {
    label: "HPD Lead Paint Violations",
    resourceId: "au8t-hgv2",
    primaryKey: "violationid",
  },
];

export interface Result {
  endpoint: Endpoint;
  status: "pass" | "fail";
  httpStatus: number | null;
  matchedKey: string | null;
  rowFields: string[];
  ms: number;
  error?: string;
}

function buildUrl(resourceId: string): string {
  // $select=:* tells Socrata to include its system fields (`:id`, `:created_at`, etc.)
  // alongside the row's domain fields. We need this for the bedbug fallback above.
  const params = new URLSearchParams({ $limit: "1", $select: ":*, *" });
  return `https://data.cityofnewyork.us/resource/${resourceId}.json?${params.toString()}`;
}

export async function checkEndpoint(
  endpoint: Endpoint,
  appToken: string | undefined,
  fetchImpl: typeof fetch = fetch,
): Promise<Result> {
  const url = buildUrl(endpoint.resourceId);
  const started = Date.now();
  const headers: Record<string, string> = {
    Accept: "application/json",
    "User-Agent": "rentguard-verify-data-sources/0.1 (+ops@rentguard.nyc)",
  };
  if (appToken) headers["X-App-Token"] = appToken;

  let res: Response;
  try {
    res = await fetchImpl(url, { headers });
  } catch (err) {
    return {
      endpoint,
      status: "fail",
      httpStatus: null,
      matchedKey: null,
      rowFields: [],
      ms: Date.now() - started,
      error: `network: ${(err as Error).message}`,
    };
  }
  const ms = Date.now() - started;

  if (!res.ok) {
    const body = await res.text().catch(() => "");
    return {
      endpoint,
      status: "fail",
      httpStatus: res.status,
      matchedKey: null,
      rowFields: [],
      ms,
      error: `http ${res.status}: ${body.slice(0, 200)}`,
    };
  }

  let data: unknown;
  try {
    data = await res.json();
  } catch (err) {
    return {
      endpoint,
      status: "fail",
      httpStatus: res.status,
      matchedKey: null,
      rowFields: [],
      ms,
      error: `non-json response: ${(err as Error).message}`,
    };
  }

  if (!Array.isArray(data)) {
    return {
      endpoint,
      status: "fail",
      httpStatus: res.status,
      matchedKey: null,
      rowFields: [],
      ms,
      error: "expected array response, got " + typeof data,
    };
  }

  if (data.length === 0) {
    // Empty datasets are technically valid (e.g. a freshly created snapshot)
    // but for our purposes, every dataset listed should have data — fail loudly.
    return {
      endpoint,
      status: "fail",
      httpStatus: res.status,
      matchedKey: null,
      rowFields: [],
      ms,
      error: "empty array — dataset returned no rows for $limit=1",
    };
  }

  const row = data[0] as Record<string, unknown>;
  const rowFields = Object.keys(row);

  const candidates = [endpoint.primaryKey, ...(endpoint.alternatePrimaryKeys ?? [])];
  const matched = candidates.find((k) => k in row) ?? null;

  if (!matched) {
    return {
      endpoint,
      status: "fail",
      httpStatus: res.status,
      matchedKey: null,
      rowFields,
      ms,
      error: `none of [${candidates.join(", ")}] present in row. fields: ${rowFields.slice(0, 25).join(", ")}${rowFields.length > 25 ? "…" : ""}`,
    };
  }

  return {
    endpoint,
    status: "pass",
    httpStatus: res.status,
    matchedKey: matched,
    rowFields,
    ms,
  };
}

function formatResult(r: Result): string {
  const tag = r.status === "pass" ? "PASS" : "FAIL";
  const hp = r.httpStatus ? `HTTP ${r.httpStatus}` : "no-response";
  const head = `[${tag}] ${r.endpoint.resourceId.padEnd(10)} ${hp.padEnd(8)} ${r.ms}ms  ${r.endpoint.label}`;
  if (r.status === "pass") {
    return `${head}\n        primary key '${r.matchedKey}' present (row had ${r.rowFields.length} fields)`;
  }
  return `${head}\n        ERROR: ${r.error}`;
}

async function main(): Promise<void> {
  loadDotenv();
  const appToken = process.env.NYC_OPEN_DATA_APP_TOKEN;
  console.log(
    `RentGuard data-source verifier — ${ENDPOINTS.length} endpoints, ${
      appToken ? "with" : "WITHOUT"
    } NYC_OPEN_DATA_APP_TOKEN\n`,
  );

  const results: Result[] = [];
  // Sequential is fine here — 8 endpoints, and we don't want to look like we're
  // probing the API from multiple connections at once on the unauthenticated tier.
  for (const ep of ENDPOINTS) {
    const r = await checkEndpoint(ep, appToken);
    console.log(formatResult(r));
    results.push(r);
  }

  const failed = results.filter((r) => r.status === "fail");
  console.log(
    `\nResult: ${results.length - failed.length}/${results.length} passed, ${failed.length} failed`,
  );
  if (failed.length > 0) {
    process.exit(1);
  }
}

// Only run when executed directly (not when imported by tests).
const invokedDirectly =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("verify-data-sources.ts") === true ||
  process.argv[1]?.endsWith("verify-data-sources.js") === true;
if (invokedDirectly) {
  main().catch((err) => {
    console.error("verifier crashed:", err);
    process.exit(1);
  });
}
