// Standardized error envelope shared across /v1/* routes.
//
// Shape: `{error: {code, message, requestId, details?}}`. Used for
// validation failures, auth failures, rate-limit hits, and unexpected
// handler crashes. Domain-level discriminated outcomes (e.g. `ambiguous`,
// `email_gate`, `success`) are NOT errors — they keep their existing
// `{kind: ...}` shape.
//
// Mid-stream errors on /v1/lookup/stream MUST continue to use the NDJSON
// `{event: "phase"|"complete"|...}` format. The envelope is for top-level
// HTTP responses only.
//
// requestId is a UUID generated by request-id middleware (see app.ts).
// Surface it in logs and in user-facing messages so support can correlate
// a complaint to a specific request.
import type { Context } from 'hono';
import type { ZodIssue } from 'zod';

export type ErrorCode =
  | 'validation_failed'
  | 'unauthorized'
  | 'forbidden'
  | 'not_found'
  | 'rate_limited'
  | 'payment_required'
  | 'internal_error';

export type ErrorEnvelope = {
  error: {
    code: ErrorCode;
    message: string;
    requestId: string;
    details?: unknown;
  };
};

const CODE_TO_STATUS: Record<ErrorCode, number> = {
  validation_failed: 400,
  unauthorized: 401,
  forbidden: 403,
  not_found: 404,
  rate_limited: 429,
  payment_required: 402,
  internal_error: 500,
};

export class AppError extends Error {
  readonly code: ErrorCode;
  readonly status: number;
  readonly details?: unknown;
  constructor(code: ErrorCode, message: string, details?: unknown) {
    super(message);
    this.name = 'AppError';
    this.code = code;
    this.status = CODE_TO_STATUS[code];
    this.details = details;
  }
}

export function isAppError(err: unknown): err is AppError {
  return err instanceof AppError;
}

export function fromZodIssues(issues: ZodIssue[]): AppError {
  return new AppError('validation_failed', 'Request failed validation.', {
    issues: issues.map((i) => ({ path: i.path, message: i.message, code: i.code })),
  });
}

export function toEnvelope(err: AppError, requestId: string): ErrorEnvelope {
  return {
    error: {
      code: err.code,
      message: err.message,
      requestId,
      ...(err.details === undefined ? {} : { details: err.details }),
    },
  };
}

// Helper for routes/middleware that have a Context handy. Returns the
// JSON response with the envelope and the matching HTTP status.
export function envelopeResponse(c: Context, err: AppError) {
  const requestId = c.get('requestId') ?? 'unknown';
  // hono c.json doesn't type the second arg as our specific status union;
  // cast through a known-good numeric so TS infers correctly.
  return c.json(toEnvelope(err, requestId), err.status as 400 | 401 | 403 | 404 | 429 | 402 | 500);
}
