// Build-time script: parses docs/legal/disclaimers.md and emits
// frontend/lib/legal/disclaimers.json + disclaimers.ts.
// Run via: npm run build:disclaimers  (called automatically by dev/build/test).

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const md = readFileSync(join(__dirname, '../../docs/legal/disclaimers.md'), 'utf8');

function extractSection(anchor: string): string {
  const re = new RegExp(
    `<!-- BEGIN ${anchor} -->\\n([\\s\\S]*?)\\n<!-- END ${anchor} -->`,
    'm',
  );
  const m = md.match(re);
  if (!m) throw new Error(`section ${anchor} not found in disclaimers.md`);
  return m[1].trim();
}

const out = {
  preOutputFraming: extractSection('preOutputFraming'),
  fareActFraming: extractSection('fareActFraming'),
  affiliateClickThrough: extractSection('affiliateClickThrough'),
  affiliateLongForm: extractSection('affiliateLongForm'),
  weAreNotFooter: extractSection('weAreNotFooter'),
};

const legalDir = join(__dirname, '../lib/legal');
mkdirSync(legalDir, { recursive: true });

writeFileSync(join(legalDir, 'disclaimers.json'), JSON.stringify(out, null, 2));
writeFileSync(
  join(legalDir, 'disclaimers.ts'),
  [
    '// AUTO-GENERATED by scripts/build-disclaimers.ts. Do not edit directly.',
    "// Edit docs/legal/disclaimers.md and run `npm run build:disclaimers`.",
    "import json from './disclaimers.json' with { type: 'json' };",
    'export const DISCLAIMERS = json as Readonly<{',
    '  preOutputFraming: string;',
    '  fareActFraming: string;',
    '  affiliateClickThrough: string;',
    '  affiliateLongForm: string;',
    '  weAreNotFooter: string;',
    '}>;',
    '',
  ].join('\n'),
);

console.log('disclaimers built →', legalDir);
